apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-add-ui
  namespace: microtodo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-add-ui
  template:
    metadata:
      labels:
        app: todo-add-ui
    spec:
      containers:
      - name: todo-add-ui
        image: acraadibhai.azurecr.io/addtask-todo-ui:v1
        ports:
        - containerPort: 80
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:aadiserver.database.windows.net,1433;Database=aadi-db;Uid=useradmin;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

